# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{postrank-api}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Ilya Grigorik"]
  s.date = %q{2010-06-03}
  s.description = %q{PostRank API Wrapper}
  s.email = %q{ilya@igvita.com}
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    "README.md",
     "Rakefile",
     "VERSION",
     "lib/postrank-api.rb",
     "lib/postrank-api/api.rb",
     "spec/api_spec.rb"
  ]
  s.homepage = %q{http://github.com/postrank/postrank-api}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.required_ruby_version = Gem::Requirement.new(">= 1.9.1")
  s.rubyforge_project = %q{postrank-api}
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{PostRank API Wrapper}
  s.test_files = [
    "spec/api_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<eventmachine>, [">= 0.12.9"])
      s.add_runtime_dependency(%q<em-http>, [">= 0"])
      s.add_runtime_dependency(%q<em-synchrony>, [">= 0"])
    else
      s.add_dependency(%q<eventmachine>, [">= 0.12.9"])
      s.add_dependency(%q<em-http>, [">= 0"])
      s.add_dependency(%q<em-synchrony>, [">= 0"])
    end
  else
    s.add_dependency(%q<eventmachine>, [">= 0.12.9"])
    s.add_dependency(%q<em-http>, [">= 0"])
    s.add_dependency(%q<em-synchrony>, [">= 0"])
  end
end

